from fastapi import APIRouter

from app.config import settings as app_config
from app.api import admin, agents, ai_accounts, analytics, approval_rules, approvals, apps_overview, audit, auth, brain, brain_mcp, brains, command_policies, computer_use, docker_apps, downloads, event_triggers, features, feedback, health, integrations, kiosk, knowledge, knowledge_feeds, license as license_api, meeting_rooms, meetings, memory, mcp_agent, mcp_exchange, mcp_msgraph, mcp_msgraph_external, mcp_servers, notifications, oauth_as, presence, ratings, roles, schedules, secrets, skill_marketplace, skills_catalog, tasks, teams, telegram_actions, templates, todos, url_allowlist, user_profiles, version, vertical_packs, webhooks, ws, settings

api_router = APIRouter()
api_router.include_router(admin.router)
api_router.include_router(roles.router)
api_router.include_router(analytics.router)
api_router.include_router(downloads.router)
api_router.include_router(approvals.router)
api_router.include_router(computer_use.router)
api_router.include_router(audit.router)
api_router.include_router(auth.router)
api_router.include_router(agents.router)
api_router.include_router(meetings.router)
api_router.include_router(ai_accounts.router)
api_router.include_router(brains.router)
api_router.include_router(docker_apps.router)
api_router.include_router(apps_overview.router)
api_router.include_router(presence.router)
api_router.include_router(event_triggers.router)
api_router.include_router(features.router)
api_router.include_router(feedback.router)
api_router.include_router(health.router)
api_router.include_router(integrations.router)
# Kiosk endpoints are unauthenticated by design (local Pi browser) — only mount
# them on an actual kiosk device. See config.kiosk_enabled.
if app_config.kiosk_enabled:
    api_router.include_router(kiosk.router)
api_router.include_router(brain.router)
api_router.include_router(knowledge.router)
api_router.include_router(knowledge_feeds.router)
api_router.include_router(memory.router)
api_router.include_router(mcp_agent.router)
api_router.include_router(brain_mcp.router)
api_router.include_router(mcp_msgraph.router)
api_router.include_router(mcp_msgraph_external.router)
api_router.include_router(mcp_exchange.router)
api_router.include_router(oauth_as.oauth_router)
api_router.include_router(mcp_servers.router)
api_router.include_router(notifications.router)
api_router.include_router(ratings.router)
api_router.include_router(tasks.router)
api_router.include_router(templates.router)
api_router.include_router(todos.router)
api_router.include_router(schedules.router)
api_router.include_router(skill_marketplace.router)
api_router.include_router(skills_catalog.router)
api_router.include_router(webhooks.router)
api_router.include_router(telegram_actions.router)
api_router.include_router(version.router)
api_router.include_router(ws.router)
api_router.include_router(settings.router)
api_router.include_router(meeting_rooms.router)
api_router.include_router(teams.router)
api_router.include_router(approval_rules.router)
api_router.include_router(command_policies.router)
api_router.include_router(url_allowlist.router)
api_router.include_router(secrets.router)
api_router.include_router(license_api.router)
api_router.include_router(user_profiles.router)
api_router.include_router(vertical_packs.router)
