// Architektur-/Schnittstellen-Referenz — faktenbasiert aus dem Code inventarisiert
// (Orchestrator app/api/*, core/msgraph_mcp.py, services/realtime_voice_session.py,
// app/api/ws.py, app/models/*, docs/ARCHITECTURE.md). Reine Referenzdaten; das
// Rendering passiert in ./page.tsx. Bei neuen Endpunkten/Tools hier ergänzen.

export type Group = { title: string; items: string[] };

// ── HTTP-API-Endpunkte (Basis-Prefix /api/v1). Auth: [auth] Session/JWT,
//    [admin] Admin, [auth|agent] User oder Agent-Token, [agent] agent-facing,
//    [public] kein FastAPI-Auth-Dependency (meist Ticket/Bearer/Webhook-Token). ──
export const API_GROUPS: Group[] = [
  { title: "Auth & Users (/auth)", items: [
    "POST /auth/register — Registrierung (Setup-Token für ersten Admin) [public]",
    "POST /auth/login — Login [public]",
    "POST /auth/logout — Logout [public]",
    "POST /auth/refresh — Token-Refresh [public]",
    "GET /auth/registration-status — ob Registrierung offen ist [public]",
    "GET /auth/sso/providers — verfügbare SSO-Provider [public]",
    "GET /auth/sso/{provider}/login — SSO-Login starten [public]",
    "GET /auth/sso/{provider}/callback — SSO-Callback [public]",
    "GET /auth/me — eigenes Profil [auth]",
    "GET /auth/me/photo — eigenes Profilfoto [auth]",
    "GET /auth/users — User listen [admin]",
    "POST /auth/users — User anlegen [admin]",
    "PATCH /auth/users/{user_id} — User ändern [admin]",
    "DELETE /auth/users/{user_id} — User löschen [admin]",
  ]},
  { title: "Agents (/agents)", items: [
    "GET /agents/ — Agentenliste [auth]",
    "POST /agents/ — Agent erstellen [auth]",
    "GET /agents/{id} — Agent-Details [auth]",
    "DELETE /agents/{id} — Agent löschen [auth]",
    "POST /agents/{id}/start|stop|restart|update — Lifecycle steuern [auth]",
    "POST /agents/{id}/autonomy-level — Autonomie-Level setzen [auth]",
    "GET|PUT /agents/{id}/autonomy-matrix — Autonomie-Matrix lesen/setzen [auth]",
    "POST /agents/{id}/parallel-sessions — parallele Sessions setzen [auth]",
    "PATCH /agents/{id}/llm-config|model|ai-account — Modell/Provider ändern [auth]",
    "PATCH /agents/{id}/appearance|name|budget|idle-stop — Stammdaten ändern [auth]",
    "PUT /agents/{id}/interaction-model — Interaktionsmodell (Voice/Chat) setzen [auth]",
    "GET /agents/{id}/stats — Statistiken [auth]",
    "GET|PUT /agents/{id}/knowledge — knowledge.md lesen/schreiben [auth]",
    "POST|GET|DELETE /agents/{id}/files[/upload|/download] — Workspace-Dateien [auth]",
    "POST /agents/{id}/message — Nachricht an Agent senden [auth|agent]",
    "GET /agents/{id}/chat/sessions|history — Chat lesen [auth]",
    "PATCH|DELETE /agents/{id}/chat/sessions[/{sid}] — Sessions verwalten [auth]",
    "PATCH /agents/{id}/permissions|browser-mode|resource-limits — Rechte/Limits [auth]",
    "GET|PATCH /agents/{id}/integrations|mcp-servers|mounts — Anbindungen [auth]",
    "GET|POST|DELETE /agents/{id}/proactive — Proaktiv-Trigger [auth]",
    "GET|PUT|DELETE /agents/{id}/telegram[/send|/regenerate-key] — Telegram [auth/agent]",
    "GET|POST|PUT|DELETE /agents/{id}/skills[/{name}|/install] — Agent-Skills [auth]",
    "DELETE /agents/{id}/webhook — Webhook-Config löschen [auth]",
    "GET /agents/permissions|models — Permission-/Modell-Katalog [auth]",
    "GET /agents/team/directory|messages|delegations|conversation|poll-reply — Team [auth|agent]",
    "GET /agents/logs — Agent-Logs (agent-facing) [agent]",
  ]},
  { title: "Tasks, Todos, Schedules, Trigger", items: [
    "GET|POST /tasks/ — Tasks listen/anlegen [auth|agent]",
    "POST /tasks/batch — Tasks im Batch anlegen [auth|agent]",
    "POST /tasks/estimate — Kosten schätzen [auth]",
    "GET /tasks/summary|cost-attribution — Auswertung [auth]",
    "GET /tasks/{id}[/steps] — Task-Details/Schritte [auth|agent]",
    "POST /tasks/{id}/cancel|retain|release — Task steuern [auth]",
    "DELETE /tasks/{id} — Task löschen [auth]",
    "GET|POST|PATCH|DELETE /todos/agents/{id} bzw. /todos/{id} — Todos [auth|agent]",
    "GET|PUT|PATCH /todos/agent/list|bulk|{id}/complete — Todos (agent) [agent]",
    "GET|POST|PUT|DELETE /schedules/ — Cron/Interval-Jobs [auth|agent]",
    "POST /schedules/{id}/trigger|pause|resume — Job steuern [auth|agent]",
    "GET|POST|PUT|DELETE /event-triggers — Ereignis-Trigger [auth]",
    "POST /event-triggers/{id}/toggle|test — Trigger schalten/testen [auth]",
    "…/event-triggers/for-agent — Trigger (agent-facing) [agent]",
  ]},
  { title: "Chat/Voice & WebSockets (/ws)", items: [
    "POST /ws/ticket — Einmal-Ticket für WS-Auth (30s TTL) [auth]",
    "WS /ws/agents/{id}/chat — Text-Chat-Stream [Ticket]",
    "WS /ws/agents/{id}/voice — Realtime-/Klassik-Voice [Ticket]",
    "WS /ws/agents/{id}/logs — Agent-Log-Stream [Ticket]",
    "WS /ws/notifications — Notification-Push [Ticket]",
    "WS /ws/logs — globaler Log-Stream [Ticket]",
    "POST /meetings/transcribe — Audio transkribieren (STT-Service → OpenAI-Fallback) [auth]",
  ]},
  { title: "Approvals & Governance", items: [
    "POST /approvals/request — Freigabe anfordern (agent) [agent]",
    "GET /approvals/check/{id} — Freigabestatus pollen (agent) [agent]",
    "GET /approvals/pending|all — offene/alle Freigaben [auth]",
    "POST /approvals/{id}/approve|deny — entscheiden [auth]",
    "GET|POST|PATCH|DELETE /approval-rules — Freigaberegeln [auth]",
    "GET /approval-rules/level-presets — Autonomie-Presets [public]",
    "GET|POST|PATCH|DELETE /command-policies — Befehls-Allow/Deny-Regeln [auth]",
    "GET /command-policies/for-agent/{id} — effektive Policy (agent) [agent]",
    "GET|POST|DELETE /url-allowlist/templates[/entries] — URL-Allowlists [auth]",
    "…/url-allowlist/agent/{id} — Agent-Allowlist + check (agent) [auth/agent]",
    "POST /audit/log — Audit-Eintrag (agent) [agent]",
    "GET /audit/logs[/summary|/{id}] — Audit-Trail [auth]",
  ]},
  { title: "Knowledge, Brain & Second Brains", items: [
    "GET|POST|PUT|DELETE /knowledge/entries — Wissensbasis [auth]",
    "GET /knowledge/tags|graph — Tags / Wissens-Graph [auth]",
    "POST|GET /knowledge/agent/write|search|read/{title} — Wissen (agent) [agent]",
    "GET /brain/graph|search|related/{id} — Brain (User) [auth]",
    "…/brain/agent/* — Brain lesen/schreiben/suchen (agent) [agent]",
    "POST /brain/backfill — Brain neu indexieren [auth]",
    "GET|POST|PATCH|DELETE /brains/ — Vaults verwalten [auth]",
    "GET|PUT|DELETE /brains/{id}/file, /tree, /graph — Vault-Inhalt [auth]",
    "POST /brains/{id}/mcp/token — Vault-MCP-Token [auth]",
    "POST /mcp/brains/{slug} — Vault als externer MCP-Server (Bearer) [public]",
    "GET|POST|PATCH|DELETE /knowledge-feeds — externe Feeds [auth/public]",
  ]},
  { title: "MCP-Endpunkte (agent-/extern-facing)", items: [
    "POST /mcp/agents/{id} — MCP-Endpoint des Agenten (Orchestrator-Tools) [Bearer]",
    "POST /mcp/exchange-onprem/{id} — On-Prem-Exchange (EWS) MCP [Bearer]",
    "POST /mcp/msgraph/{id} — MS-Graph-MCP pro Agent [Bearer]",
    "POST /mcp/msgraph — externer MS-Graph-MCP (OAuth, read-only, OpenWebUI) [OAuth]",
    "GET|POST|PATCH|DELETE /mcp-servers — registrierte externe MCP-Server [auth/admin]",
    "POST /mcp-servers/probe — Verbindung testen [admin]",
  ]},
  { title: "Meetings & Teams", items: [
    "GET|POST|DELETE /meeting-rooms/ — Meeting-/Taskforce-Räume [auth]",
    "POST /meeting-rooms/{id}/start|stop — Meeting steuern [auth]",
    "POST /meeting-rooms/schedule — Meeting planen [auth]",
    "GET|POST /meeting-rooms/{id}/deliverable/files|file|launch — Taskforce-Deliverable [auth]",
    "GET|POST|PATCH|DELETE /teams/ — Teams verwalten [auth]",
    "POST /teams/{id}/members|tasks — Mitglied/Task hinzufügen [auth]",
    "PATCH /teams/{id}/lead — Team-Lead setzen [auth]",
  ]},
  { title: "Integrationen, AI-Accounts & Settings", items: [
    "GET /integrations/ — Integrationen [auth]",
    "GET /integrations/{provider}/auth|callback|token — OAuth-Flow [auth/public/admin]",
    "POST /integrations/{provider}/pat|auth-json|device-auth/* — Auth hinterlegen [auth/admin]",
    "GET|POST|PATCH|DELETE /ai-accounts/ — LLM-Provider-Zugänge [auth]",
    "GET /ai-accounts/realtime-models — Voice-fähige Modelle [auth]",
    "GET|PATCH /settings/ — globale Settings [auth/admin]",
    "GET /settings/voice|agent-mounts|idle-stop — Teil-Settings [auth]",
    "PUT /settings/msgraph-mcp-external — externen Graph-MCP konfigurieren [admin]",
  ]},
  { title: "Skills & Vertical Packs", items: [
    "GET|POST|PUT|DELETE /skills/marketplace[/{id}] — Skill-Marktplatz [auth]",
    "POST /skills/marketplace/{id}/approve|reject|assign|rollback/{v} — kuratieren [auth]",
    "GET /skills/marketplace/{id}/versions — Versionshistorie [auth]",
    "…/skills/agent/* — install/available/search/record-usage/propose (agent) [agent]",
    "GET /skills/catalog[/refresh] — installierbarer Katalog [public]",
    "GET|POST /vertical-packs[/{slug}/provision] — Branchen-Pakete [auth]",
    "GET|POST|PUT|DELETE /templates — Agent-Templates [auth]",
    "POST /templates/{id}/create-agent|publish|unpublish — Templates nutzen [auth]",
  ]},
  { title: "Notifications, Ratings, Analytics, Health", items: [
    "POST /notifications/ — Notification erzeugen (agent) [agent]",
    "GET /notifications/[count] — listen/zählen [auth]",
    "POST /notifications/{id}/read|respond, /read-all — verwalten [auth]",
    "POST /notifications/register-device — Push-Gerät (iOS) [auth]",
    "POST /ratings/tasks/{id}/rate, /task-self-rate, /skill-usage — Bewertungen [auth/agent]",
    "GET /ratings/agents/{id}/ratings|improvement-report — Reports [auth]",
    "GET /analytics/overview|skills|agents[/{id}] — Kennzahlen [auth]",
    "GET /health/test-runs[/latest|/{id}], /dashboard, /auto-metrics — Health [auth]",
    "POST /health/test-runs/trigger — Test-Run auslösen [auth]",
  ]},
  { title: "Secrets, Roles, Admin, Feature-Flags", items: [
    "GET|POST|PATCH|DELETE /secrets — verschlüsselte Secrets [auth]",
    "POST|DELETE /secrets/agent/{id}/{sid} — Secret an Agent binden [auth]",
    "GET|POST|PUT|DELETE /roles/ — Rollen/Rechtebündel [auth]",
    "PUT /roles/users/{id}/assign|budget — Rolle/Budget zuweisen [auth]",
    "GET /roles/me/permissions — eigene Rechte [auth]",
    "GET /admin/overview, /agents/{id}/stats — Admin-Übersicht [admin]",
    "POST /admin/assign-agent|distribute-agent — Agenten zuweisen [admin]",
    "GET|PUT|DELETE /features/[{name}] — Feature-Flags [auth/admin]",
    "GET|POST|DELETE /license/[apply|features] — Lizenz [admin/auth]",
  ]},
  { title: "Computer-Use, Apps, Downloads, Telegram, Presence, Webhooks, OAuth, Version", items: [
    "POST|GET|DELETE /computer-use/sessions[/{id}] — Desktop-Bridge-Sessions [auth]",
    "POST /computer-use/sessions/{id}/command — Desktop-Befehl [auth|agent]",
    "GET /computer-use/sessions/{id}/screenshot|status|audit — Session-Infos [auth]",
    "WS /ws/computer-use/bridge — Desktop-Bridge (Root) [Bridge-Token]",
    "GET|POST /apps + /agents/{id}/apps/* — Docker-Apps der Agenten [auth]",
    "GET /download/bridge/mac|windows — Bridge-Installer [public]",
    "POST /telegram/send-message|send-photo|send-document|… (28 Aktionen, agent) [agent]",
    "POST /presence/heartbeat, GET /presence/online — Online-Präsenz [auth/admin]",
    "GET|PATCH|POST /webhooks/agents/{id}/settings|regenerate-token|events — Webhooks [auth]",
    "POST /webhooks/agents/{id} — eingehender Agent-Webhook [Webhook-Token]",
    "POST /webhooks/github — GitHub-Webhook-Empfänger [Signatur]",
    "POST /oauth/register|token, GET|POST /oauth/authorize — OAuth-AS [public]",
    "GET /.well-known/oauth-* — OAuth-Discovery (Root) [public]",
    "GET /version/[changelog] — Version + Update-Check [public]",
    "…/kiosk/* — lokales Pi-Kiosk (nur bei kiosk_enabled) [public]",
    "GET|POST|PATCH|DELETE /feedback/ — Nutzer-Feedback [auth/admin]",
    "GET|POST|PATCH|DELETE /user-profiles/me/* — adaptives Nutzerprofil [auth]",
  ]},
];

// ── MS-Graph-MCP-Tools (61: 31 READ / 30 WRITE). W = Schreib-Tool. ──
export const GRAPH_GROUPS: Group[] = [
  { title: "Profil & Suche", items: [
    "ms_get_user_info() — M365-Profil (Name/E-Mail/Titel)",
    "ms_search(query, types?, limit?) — universelle Suche (Mail/Termine/Dateien/Teams)",
    "ms_search_people(query) — Person → E-Mail (Fallback: Entra-Verzeichnis)",
    "ms_search_files(query, limit?) — OneDrive/SharePoint durchsuchen",
    "ms_recent_files(limit?) — zuletzt bearbeitete Dateien",
    "ms_insights(kind?, limit?) — trending/used/shared Dokumente",
    "ms_graph_get(path, params?) — Fallback read-only GET auf beliebigen Graph-Endpoint",
  ]},
  { title: "Mail (Outlook)", items: [
    "ms_list_emails(folder?, search?, sender?, subject?, limit?) — Ordner listen/filtern",
    "ms_read_email(email_id) — vollen Inhalt lesen",
    "ms_list_attachments(email_id) / ms_read_attachment(email_id, attachment_id) — Anhänge",
    "W ms_send_email(to, subject, body, cc?, draft?) — senden oder Entwurf",
    "W ms_reply_email(email_id, body, reply_all?, draft?) — antworten",
    "W ms_forward_email(email_id, to, comment?, draft?) — weiterleiten",
    "W ms_delete_email / ms_move_email / ms_mark_email_read — verwalten",
  ]},
  { title: "Kalender & Meetings", items: [
    "ms_list_calendar_events(days_ahead?, limit?) — Termine listen",
    "ms_find_meeting_times(attendees, duration_minutes?) — freie Slots vorschlagen",
    "W ms_create_calendar_event(subject, start, end, attendees?, online_meeting?) — anlegen",
    "W ms_update_calendar_event / ms_respond_event / ms_cancel_event — ändern/antworten/absagen",
    "W ms_create_online_meeting(subject, start, end) — Teams-Meeting + Join-Link",
  ]},
  { title: "Dateien / OneDrive / SharePoint", items: [
    "ms_list_folder(path?) / ms_read_file_content(path) — OneDrive lesen",
    "ms_list_sites(query?) / ms_list_site_lists(site_id) / ms_list_list_items(site_id, list_id) — SharePoint",
    "W ms_create_folder / ms_upload_text_file / ms_share_file — anlegen/teilen",
    "W ms_delete_item / ms_move_item / ms_copy_item — verwalten",
  ]},
  { title: "Excel & OneNote", items: [
    "ms_excel_read(path, worksheet, range) — Zellbereich lesen",
    "W ms_excel_write(path, worksheet, range, values) — Zellbereich schreiben",
    "ms_list_notebooks() / ms_read_note_page(page_id) — OneNote",
  ]},
  { title: "Personen, Presence, Kontakte", items: [
    "ms_presence(email?) — Teams-Anwesenheit",
    "ms_list_contacts(limit?) — Kontakte listen",
    "W ms_create_contact / ms_update_contact / ms_delete_contact — Kontakte pflegen",
  ]},
  { title: "Teams (Chats & Kanäle)", items: [
    "ms_list_teams() / ms_list_channels(team_id) — Teams/Kanäle",
    "ms_list_channel_messages / ms_list_chats / ms_list_chat_messages — Nachrichten lesen",
    "W ms_send_teams_message(team_id, channel_id, message) — Kanal posten",
    "W ms_send_chat_message(chat_id, message) — Chat posten",
  ]},
  { title: "Aufgaben (To-Do & Planner)", items: [
    "ms_list_tasks(list_id?, include_completed?) — To-Do listen",
    "W ms_create_task / ms_update_task / ms_complete_task / ms_delete_task — To-Do",
    "ms_list_planner_plans() / ms_list_planner_tasks(plan_id?) — Planner lesen",
    "W ms_create_planner_task / ms_update_planner_task / ms_delete_planner_task — Planner",
  ]},
];

// ── MCP-Server & Tools, die ein Agent-Container aufrufen kann ──
export const MCP_GROUPS: Group[] = [
  { title: "Orchestrator-MCP (Agent-Steuerung, POST /mcp/agents/{id})", items: [
    "send_task(prompt, title?) — Aufgabe an diesen Agenten einreihen",
    "get_task_status(task_id) / list_recent_tasks(limit?) — Task-Status",
    "get_agent_status() — Zustand/Rolle/Aktivität",
    "list_my_team() — eigenes Team + Mitglieder/Rollen/Lead",
    "write_knowledge(title, content, tags?) — in die Wissensbasis schreiben",
    "computer_use(action, session_id?, params?) — Desktop steuern (Bridge)",
  ]},
  { title: "Built-in Container-MCP (in Agent-CLAUDE.md ausgewiesen)", items: [
    "mcp-memory: memory_save, memory_search (semantisch), memory_list, memory_delete",
    "mcp-orchestrator: list_team, list_my_team, create_task, list_tasks, send_message, write_knowledge",
    "mcp-orchestrator: create_schedule, list_schedules, manage_schedule",
    "mcp-orchestrator: list_todos, update_todos, complete_todo",
    "mcp-notifications: send_telegram, notify_user, request_approval",
    "mcp-knowledge: brain_search, brain_get, brain_contribute",
    "Skills: skill_search, skill_install · Self-Diagnose: read_logs",
    "Native: WebSearch, WebFetch, bash/grep/find, /workspace/.claude/skills/*",
  ]},
  { title: "Second-Brain-MCP (POST /mcp/brains/{slug}, Bearer)", items: [
    "brain_search(query, limit?) / brain_read(path) / brain_list() / brain_tree() — Vault lesen",
    "brain_write(path, content, overwrite?) / brain_delete(path) — Vault schreiben (nur rw)",
  ]},
  { title: "On-Prem-Exchange-MCP (EWS, POST /mcp/exchange-onprem/{id})", items: [
    "ex_whoami — Verbindungs-/Auth-Test (welches Postfach)",
    "ex_list_emails / ex_read_email — Postfach lesen",
    "ex_send_email / ex_reply_email / ex_forward_email — Versand",
    "ex_delete_email / ex_move_email / ex_mark_email_read — Mail-Verwaltung",
    "ex_list_calendar_events / ex_create|update|cancel_calendar_event — Kalender",
  ]},
];

// ── Voice-Layer (Realtime-Cockpit): kuratierte Tools ──
export const VOICE_TOOLS: Group[] = [
  { title: "Schnelle Tools (aus DB/Redis, kein Agenten-Turn)", items: [
    "get_agent_status() — Status/Tätigkeit/Queue",
    "list_agent_tasks(limit?) — letzte Tasks + Outcome",
    "get_agent_settings() — Modell/Modus/Autonomie/Budget",
    "get_agent_activity() — Live-Feed der laufenden Arbeit",
    "web_search(query, max_results?) — öffentliche Websuche",
    "search_knowledge(query) — eigenes Wissen/Memory",
    "save_memory(content, key?) — ins Langzeitgedächtnis",
    "list_todos() — offene Todos",
    "set_autonomy(level l1–l4) / set_agent_model(model) — Agent steuern",
    "get_delegated_tasks() — im Call delegierte Tasks",
  ]},
  { title: "Delegation (echte Agenten-Turns, asynchron)", items: [
    "ask_agent(instruction) — echte Arbeit delegieren (Dateien, M365, Code, Reasoning)",
    "delegate_tasks(tasks[]) — mehrere Aufgaben PARALLEL (max 5)",
    "refine_task(instruction, task_id?) — laufende Aufgabe korrigieren (behält Kontext)",
  ]},
];

export const WS_EVENTS: Group[] = [
  { title: "WS /ws/agents/{id}/chat", items: [
    "→ Client→Server: {text, session_id?, images?, model?} · {action:'stop'} · {text:'/reset'}",
    "← Server→Client: ready · session · queued · text · tool_call · image · file · done · error · cancelled · security_block",
  ]},
  { title: "WS /ws/agents/{id}/voice", items: [
    "→ Client→Server: audio_chunk{b64} · commit{language?} · interrupt · ping",
    "← Server→Client: ready{mode} · transcript · response · audio_chunk{b64,pcm/mp3} · clear_audio · activity · media · delegate · delegate_done · tts_start/tts_end · done · error · pong",
  ]},
  { title: "Realtime-Engines", items: [
    "bedrock → nova_sonic: amazon.nova-2-sonic-v1:0 / amazon.nova-sonic-v1:0",
    "azure-realtime → azure_realtime: gpt-realtime / gpt-4o-realtime-preview / gpt-4o-mini-realtime-preview",
    "sonst: klassische Pipeline STT → LLM → TTS (Push-to-Talk)",
  ]},
];

// ── Datenbank-Modelle (PostgreSQL, gruppiert) ──
export const DB_GROUPS: Group[] = [
  { title: "Agenten & Teams", items: [
    "Agent — deployter Agent-Container (state, model, mode, config, budget, autonomy, webhook)",
    "AgentAccess — welche User auf einen Agenten zugreifen dürfen",
    "AgentMessage — Nachrichten zwischen Agenten",
    "AgentTemplate — wiederverwendbare Agenten-Blueprints",
    "Team — Agenten-Gruppe mit Lead",
  ]},
  { title: "Tasks, Todos, Scheduling, Events", items: [
    "Task / TaskStep / TaskRating — Arbeitseinheit + Event-Log + Bewertung",
    "AgentTodo — UI-sichtbare Todo-Items",
    "Schedule — wiederkehrende Automatisierung (Cron/Interval)",
    "EventTrigger / WebhookEvent — ereignisgesteuerte Tasks + Eingangs-Log",
    "JobState — fortsetzbarer Fortschritt langer Jobs",
  ]},
  { title: "Memory & Wissen", items: [
    "AgentMemory / AgentMemoryTag / AgentMemoryLink — Langzeitgedächtnis + Tags + Verknüpfungen",
    "KnowledgeEntry / BrainLink — Wissensbasis + Graph-Kanten",
    "KnowledgeFeed / KnowledgeFeedItem — externe Content-Feeds",
    "SecondBrain — geteilter Markdown-Vault (ro/rw, MCP)",
  ]},
  { title: "Chat & Notifications", items: [
    "ChatSession / ChatMessage — Chat-Threads + Nachrichten",
    "Notification — UI-/Telegram-Benachrichtigung",
    "DeviceToken — Push-Token (iOS)",
  ]},
  { title: "Auth, User, Rollen", items: [
    "User / CustomRole — Plattform-User + Rechtebündel",
    "UserProfile / UserProfileEvent — adaptives Nutzerprofil + Änderungslog",
    "UserMountAccess — Zugriff auf geteilte Mounts/Vaults",
    "OAuthClient / OAuthIntegration — OAuth-Clients + verbundene externe Konten",
  ]},
  { title: "Governance, Security, Config", items: [
    "AuditLog — Security-/Aktions-Audit-Trail",
    "CommandApproval / CommandPolicy / ApprovalRule / AutonomyPresetRule — Freigaben & Regeln",
    "UrlAllowlistTemplate(+Entry) / AgentUrlAllowlist — erlaubte URLs",
    "AgentSecret(+Assignment) — verschlüsselte Secrets",
    "McpServer — registrierte externe MCP-Server",
    "AIAccount — LLM-Provider-Zugänge · PlatformSettings — globale Key/Value-Settings",
  ]},
  { title: "Meetings, Skills, Feedback", items: [
    "MeetingRoom — Multi-Agent-Meeting/Taskforce (Stufen, Deliverable)",
    "Skill / AgentSkillAssignment / SkillVersion / SkillFile / SkillTaskUsage — Skill-System",
    "Feedback — Nutzer-Feedback · TestRun — automatische Test-Läufe",
  ]},
];

// ── Frontend-Routen (Next.js App Router) ──
export const FRONTEND_ROUTES: Group[] = [
  { title: "Seiten", items: [
    "/ · login · register · onboarding — Einstieg & Auth",
    "dashboard — zentrale Übersicht",
    "agents · chat — Agenten verwalten & chatten",
    "meeting-rooms — Multi-Agent-Meetings/Taskforce",
    "second-brains · knowledge — Vaults & Wissens-Graph",
    "skills · templates(apps) — Skill-Katalog & Vorlagen",
    "tasks · schedules · triggers — Aufgaben & Automatisierung",
    "approvals · audit — Freigaben & Security-Trail",
    "integrations · ai-accounts · secrets — Anbindungen & Zugänge",
    "files · analytics · health — Dateien, Auswertung, Status",
    "settings · admin · roles — Verwaltung",
    "kiosk — lokales Pi-Kiosk-Dashboard",
    "help · help/architecture — Hilfe & diese Architektur-Referenz",
  ]},
];
