"""Second Brain — semantic link graph between knowledge entries, user-scoped."""

from datetime import datetime, timezone

from sqlalchemy import Boolean, DateTime, Float, ForeignKey, Integer, String, UniqueConstraint
from sqlalchemy.orm import Mapped, mapped_column

from app.models.base import Base


class BrainLink(Base):
    """Semantic link between two KnowledgeEntry nodes in a user's Second Brain.

    Auto-generated by the brain_linker service (cosine similarity > 0.75) or
    explicitly created by agents via the brain API.
    """

    __tablename__ = "brain_links"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    user_id: Mapped[str] = mapped_column(String, index=True, nullable=False)

    source_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("knowledge_entries.id", ondelete="CASCADE"), index=True
    )
    target_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("knowledge_entries.id", ondelete="CASCADE"), index=True
    )

    similarity: Mapped[float | None] = mapped_column(Float, nullable=True)
    relation: Mapped[str | None] = mapped_column(String(200), nullable=True)
    auto_generated: Mapped[bool] = mapped_column(Boolean, default=True)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )

    __table_args__ = (
        UniqueConstraint("source_id", "target_id", name="uq_brain_link_pair"),
    )
